-- T-103: Create SERP tracking tables
-- Part of Clean v1.0 migration set

-- Search Queries: Generated by W1
CREATE TABLE IF NOT EXISTS wellness.search_queries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vertical_id UUID NOT NULL REFERENCES wellness.verticals(id),
    query_text TEXT NOT NULL,
    geo TEXT,
    intent_tag TEXT,
    priority_tier TEXT DEFAULT 'B' CHECK (priority_tier IN ('A', 'B', 'C')),
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(vertical_id, query_text, geo)
);

-- SERP Snapshots: Raw output from SerpAPI
CREATE TABLE IF NOT EXISTS wellness.serp_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    query_id UUID NOT NULL REFERENCES wellness.search_queries(id),
    raw_json JSONB NOT NULL,
    raw_hash TEXT NOT NULL, -- SHA256 of raw_json
    captured_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(query_id, captured_at)
);

-- SERP Results: Parsed organic/local results
CREATE TABLE IF NOT EXISTS wellness.serp_results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    snapshot_id UUID NOT NULL REFERENCES wellness.serp_snapshots(id),
    rank_position INTEGER NOT NULL,
    block_type TEXT NOT NULL CHECK (block_type IN ('organic', 'local_pack', 'ad', 'other')),
    title TEXT,
    url TEXT,
    domain_id UUID REFERENCES wellness.domains(id), -- Linked during W2 processing
    snippet TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(snapshot_id, rank_position, block_type)
);

CREATE INDEX IF NOT EXISTS idx_serp_results_domain_id ON wellness.serp_results(domain_id);
